version: '3'
services:
  rebels:
    image: rebels:latest
    container_name: rebels
    ports:
      - "5001:5001"  # Esponi pubblicamente la porta 5000 del container

  deathstar:
    image: deathstar:latest
    container_name: ds1
    depends_on:
      - rebels  # Imposta una dipendenza verso il service 'rebels'

  prometheus:
    image: prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"  # Expose Prometheus port

  grafana:
    image: grafana/grafana:7.5.10  # Sostituisci con la versione desiderata
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus