---
- hosts: localhost
  become: yes

  tasks:

    - name: Install Prometheus
      ### ATTENZIONE ###
      # Completare il task andando ad inserire l'istruzione per l'installazione di un nuovo pacchetto apt
      # il nome del pacchetto è 'prometheus'
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html

    - name: Prometheus configuration file
      template:
        ### ATTENZIONE ###
        # Completare il task andando ad inserire nel template i corretti valori per andare a creare un nuovo file di configurazione
        # chiamato "/etc/prometheus/prometheus.yml", con il contenuto del file config.yml.
        # Il mode deve essere 0755 e owner e group uguale a prometheus
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/template_module.html

    - name: Restart Prometheus
      systemd:
        name: prometheus
        state: restarted
        enabled: yes
        daemon_reload: yes